FamilyRails/config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  resources :moms do
    resources :children do

    end
  end

  resources :children do
    resources :toys do
    end
  end

  resources :children do
    collection do
      get '/children/:id/toys', action: "show_toys", as: "show_toys"
    end
  end

  resources :users do
  end

  resources :moms do
    get 'show_children', action: "show_children", as: "show_children"
  end

  resources :toys do

  end

end

FamilyRails/app/models/child.rb
class Child < ActiveRecord::Base
  belongs_to :mom
  has_many :toys


  def self.girl?(child)
    if child.gender == "female"
      return true
    end
  end

  def self.many_toys(child)
    if child.toys.length == 0
      return "no toys 😥"
    elsif child.toys.length == 1
      return "only one toy"
    else
      return "#{child.toys.length} toys"
    end
  end

  def self.many_siblings(child)
    mom = Mom.find(child.mom_id)
    return mom.children.length-1
  end

  def self.gender
    return ["male", "feamle"]
  end
end

FamilyRails/app/models/mom.rb
class Mom < ActiveRecord::Base
  has_many :children

  def self.kids(mom)
    if mom.children.length > 1
      return "#{mom.children.length} kids"
    elsif mom.children.length == 1
      return "1 kid"
    else
      return "no kids"
    end
  end

  def self.check_kids(mom)
    if @mom.kids!= 0
      return true
    end
  end



end

FamilyRails/app/models/toy.rb
class Toy < ActiveRecord::Base
  belongs_to :child

  def self.find_child(toys)
    return toys.first.child_id
  end
end

FamilyRails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

FamilyRails/app/controllers/children_controller.rb
class ChildrenController < ApplicationController

  before_action :find_child, only: [:show]

  def find_child
    @child = Child.find(params[:id])
  end

  def index
    @children = Child.all
  end

  def show
  end

  def new
    @mom = Mom.find(params[:mom_id])
    @child = Child.new
  end

  def create
    Child.create(child_params[:child])
    redirect_to mom_show_children_path(params[:child][:mom_id])
  end


  def show_toys
    if !params[:child_id].nil?
      child = Child.find(params[:child_id])
      @toys = child.toys.sort_by{|e| e[:kind]}
    else
      find_child
      @toys = @child.toys.sort_by{|e| e[:kind]}
    end
  end

  private

  def child_params
    params.permit(child: [:name, :gender, :age, :mom_id])
  end



end

FamilyRails/app/controllers/moms_controller.rb
class MomsController < ApplicationController
  layout "check"

  before_action :find_mom, only: [:edit, :update]

  def find_mom
    @mom = Mom.find(params[:id])
  end

  def index
    @moms = Mom.all.sort_by{|e| e[:name]}
  end

  def show
    find_mom
  end

  def show_children
    @mom = Mom.find(params[:mom_id])
    @kids = @mom.children.sort_by{|e| e[:name]}
  end

  def new
    @mom = Mom.new
  end

  def edit
  end

  def create
    Mom.create(mom_params[:mom])
    redirect_to moms_path
  end

  def update
    @mom.update(mom_params[:mom])
    redirect_to show
  end


  private

  def mom_params
    params.permit(mom: [:name, :job, :age])
  end

end

FamilyRails/app/controllers/toys_controller.rb
class ToysController < ApplicationController

  before_action :get_toy, only: [:index, :edit, :update]
  before_action :get_child, only: [:new]

  def get_child
    @child = Child.find(params[:child_id])
  end

  def get_toy
    @toy = Toy.find(params[:id])
  end


  def index
      child = Child.find(@toy.child_id)
      @toys = child.toys
  end

  def new
    @toy = Toy.new
  end

  def edit
  end

  def destroy
    Toy.destroy(params[:id])
    redirect_to show_toys_children_path(params[:child_id])
  end

  def update
    @child = Child.find(@toy.child_id)
    @toy.update(toy_params[:toy])
    redirect_to show_toys_children_path(@child.id)
  end

  def create
    Toy.create(toy_params[:toy])
    redirect_to show_toys_children_path(params[:toy][:child_id])
  end

  private

  def toy_params
    params.permit(toy: [:kind, :color, :child_id])
  end
end

FamilyRails/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

end

FamilyRails/app/helpers/application_helper.rb
module ApplicationHelper
end

FamilyRails/app/helpers/children_helper.rb
module ChildrenHelper
end

FamilyRails/app/helpers/moms_helper.rb
module MomsHelper
end

FamilyRails/app/helpers/toys_helper.rb
module ToysHelper
end

FamilyRails/app/helpers/users_helper.rb
module UsersHelper
end

FamilyRails/app/views/children/_form.html.erb
<%= form_for @child do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name, :required => true %>
	<br>
  <%= f.label :age %>:
  <%= f.text_field :age, :required => true, :numericality => {:only_integer => true} %>
  <br>
  <%= f.label 'Girl' %>
  <%= f.radio_button :gender, 'female', checked: true %>
  <br>
  <%= f.label 'Boy' %>
  <%= f.radio_button :gender, 'male' %>
  <br>
	<%= f.hidden_field :mom_id, value: @mom.id %>


  <%= @child.persisted? ? (f.submit value: "Update child", id: 'special-button') : (f.submit value: "Add child", id: 'special-button') %>
<% end %>

FamilyRails/app/views/children/index.html.erb
<div id="show_child">
  <h1> Hi child!</h1>
  <h2 class="head">Choose your name from the list</h2>
  <div id="kids_list">
    <% @children.each do |child| %>
      <li><%= link_to child.name, child_path(child.id) %></li>
    <%end %>
  </div>
</div>

FamilyRails/app/views/children/new.html.erb
<%= render "form" %>

FamilyRails/app/views/children/show.html.erb
<h1> Hi <%= @child.name %>! </h1>
  <h2 class="head"> Your profile </h2>
  <div class="child">
  <% if Child.girl?(@child) %>
    <p> you are a sweet <%=@child.age %> years old girl  </p>
  <% else %>
  <p> you are a sweet <%=@child.age %> years old boy  </p>
  <% end %>
  <p> your mother's name is <%= @child.mom.name %> </p>
  <p> you have <%= Child.many_siblings(@child) %> siblings </p>
</div class="child">

<%= link_to "your toys info", show_toys_children_path %>

FamilyRails/app/views/children/show_toys.html.erb
<%= link_to "Back to your profile", child_path(@child.id) %>
<h1 class="head">Hi <%= @child.name %>! Here are your toys </h1>
<table>
  <th>Toy </th>
  <th> Color </th>
  <% @toys.each do |toy| %>
    <tr>
      <td> <%= toy.kind %> </td>
      <td> <%= toy.color %> </td>
      <td> <%= link_to "Edit", edit_child_toy_path(toy.child_id, toy.id) %> </td>
      <td> <%= link_to 'Delete', child_toy_path(toy.child_id, toy.id), method: :delete, data: { confirm: 'Are you sure?' } %> </td>
    </tr>
  <% end %>
</table>
<br>
<br>
<%= link_to "Add a new toy", new_child_toy_path(@child.id)%>

FamilyRails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FamilyRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= link_to "Home page", users_path %>
</head>
<body>

<%= yield %>

<footer>
  <div id="footer">
  Webpage by <%= link_to "Tamar Hershi", "https://github.com/TamarHershi" %>
  <br>
  Copyright &copy; <%= Time.now.year %> All rights reserved.
  </div>
</footer>
</body>
</html>

FamilyRails/app/views/layouts/check.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Check!!!</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= link_to "Check!!!", users_path %>
</head>
<body>

<%= yield %>

<footer>
  <div id="footer">
  Webpage by <%= link_to "Tamar Hershi", "https://github.com/TamarHershi" %>
  <br>
  Copyright &copy; <%= Time.now.year %> All rights reserved.
  </div>
</footer>
</body>
</html>

FamilyRails/app/views/moms/_form.html.erb
<%= form_for @mom do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name, :require => true %>
	<br>
  <%= f.label :job %>:
  <%= f.text_field :job %>
	<br>
  <%= f.label :age %>:
  <%= f.text_field :age %>
  <br>

  <%= @mom.persisted? ? (f.submit value: "update mom", id: 'special-button') : (f.submit value: "add mom", id: 'special-button') %>
<% end %>

FamilyRails/app/views/moms/edit.html.erb
<h1>Edit your details</h1>
<%= render "form" %>

FamilyRails/app/views/moms/index.html.erb
<div class="mom">
<%= image_tag("mom2") %>
<h1>Enter your Profile</h1>
  <% @moms.each do |mom| %>
    <li><%= link_to mom.name, mom_path(mom.id) %></li>
<% end %>

<%= link_to "Add a new mom", new_mom_path %>
</div>

FamilyRails/app/views/moms/new.html.erb
<h1>Add new mom</h1>
<%= render "form" %>

FamilyRails/app/views/moms/show.html.erb
<%= link_to "Back to List of moms", moms_path %>
  <h1> <%= @mom.name %>'s Info </h1>
      <p class="mom_d"> you are working as a <%= @mom.job %> </p>
      <p class="mom_d"> you are <%= @mom.age %> years old </p>
      <p class="mom_d"> you have <%= Mom.kids(@mom) %> </p>

<div class="bottom_link">
<%= link_to "your kids info", mom_show_children_path(@mom.id) %>
<%= link_to "edit your profile", edit_mom_path %>
</div>
<%= image_tag("mom2") %>

FamilyRails/app/views/moms/show_children.html.erb
<%= link_to "back to your Profile", mom_path(@mom.id) %>
<h1> here are your kids </h1>
<% @kids.each do |kid| %>
  <p class="head"> Child Name: <%= kid.name %> </p>
  <% if Child.girl?(kid) %>
    <li> She is <%= kid.age %> years old </li>
    <li> She has <%= Child.many_toys(kid) %> </li>
  <% else %>
    <li> He is <%= kid.age %> years old </li>
    <li> He has <%= Child.many_toys(kid) %> </li>
  <% end %>
<% end %>
<br>
<br>
<%= link_to "Add a new Child", new_mom_child_path(@mom.id) %>

FamilyRails/app/views/toys/_form.html.erb
<%= form_for @toy do |f| %>
  <%= f.label :kind %>:
  <%= f.text_field :kind, :require => true %>
	<br>
  <%= f.label :color %>:
  <%= f.text_field :color, :require => true %>
  <br>
  <% if @toy.kind.nil? %>
    <%= f.hidden_field :child_id, value: @child.id %>
  <% end %>


  <%= @toy.persisted? ? (f.submit value: "update toy", id: 'special-button') : (f.submit value: "add toy", id: 'special-button') %>
<% end %>

FamilyRails/app/views/toys/edit.html.erb
<h1> Edit your Toy </h1>
<%= render "form" %>

FamilyRails/app/views/toys/index.html.erb
<h1>Here are your toys </h1>
<% @toys.each do |toy| %>
  <p> The toy is <%= toy.kind %> </p>
  <p> it's color is <%= toy.color %> </p>
  <%= link_to "Edit your toy", edit_child_toy_path(toy.child_id, toy.id) %>
<% end %>

<%= link_to "Add a new toy", new_child_toy_path %>

FamilyRails/app/views/toys/new.html.erb
<h1> Add new Toy </h1>
<%= render "form" %>

FamilyRails/app/views/users/index.html.erb
<div class="home">
  <div class="home_back">
    <p class = "mom"> <%= button_to "I am a mom", moms_path, :class => "button", :method => :get  %></p>
    <p class = "mom"> <%= button_to "I am a child", children_path, :class => "button", :method => :get  %></p>
  </div>
</div>